### PR TITLE
feat(typography): initail typography components

### PR DESCRIPTION
**Pull request by vasucp1207**
- Heading
- Link
- Image
- Para

### CODE REVIEW

**Review by cogor — CHANGES_REQUESTED** [review]

**Comment by cogor** [comment]
Props like anythingClass isn't needed, `class` attrubute on component and `:class` attribute in components will be merged 
Also for class merging need to use https://github.com/dcastil/tailwind-merge

**Comment by vasucp1207** [comment]
```ts
<Link class="text-bg-500 underline">This is a link</Link>
```
Do you mean using `class` attribute directly like this instead of  something like `link-class`

**Comment by cogor** [comment]
> ```ts
> <Link class="text-bg-500 underline">This is a link</Link>
> ```
> 
> Do you mean using `class` attribute directly like this instead of something like `link-class`

Yes

**Comment by vasucp1207** [comment]
> Props like anythingClass isn't needed, `class` attrubute on component and `:class` attribute in components will be merged Also for class merging need to use https://github.com/dcastil/tailwind-merge

It works for all typography other than `image`, if we use `class` on `Img` component it applies styles on the outer container, so we have to receive the prop inside `Img` component to use it on the `image` tag like this,

**Comment by cogor** [comment]
You're right for `Img` component we need to have a prop `imgClass`

**Comment by vasucp1207** [comment]
Closed this one due to conflicts issues

**Pull request closed without merging**
