### PR TITLE
Custom Trigger + Transition ( Dropdown )

### PR DESCRIPTION
**Pull request by CaptainZiboo**
Add parent div on slot to allow custom trigger on Dropdown and transition prop + element to Dropdown content

### CODE REVIEW

**Comment by CaptainZiboo** [comment]
I forgot to remove the conditional class hidden on dropdown not visible, cause it would break the transition, just did it

**Comment by Chank1e** [comment]
@CaptainZiboo Great work!

I think we should provide default transition then, I've added 4 transitions which depends on placement)

**Comment by CaptainZiboo** [comment]
@Chank1e I think transition depending on placement are a good idea, but we should also let people use custom transitions, then they can define they own transitions in their App.vue or View.vue, style a transition and pass it as a props to the dropdown, such as fade transitions or anything else, what do you think about that ?

**Comment by Chank1e** [comment]
ye, exactly) But you can do it with transition prop now. If no transition prop provided - default transition picked.
Also added null to type and to default value of transition prop. Now if you don't provide transition prop - default used, if you provide some name - using provided transition or if you pass empty string(`:transition=""` or just `transition`) no default transition would be used

**Comment by CaptainZiboo** [comment]
kk perfect ! Thanks for your help on that ! I'm also learning typescript and Flowbite Vue helps me a lot on that ! :p

**Comment by Chank1e** [comment]
Awesome) Merging

**Pull request merged**
