### PR TITLE
Add basic tooltip component (Issue #71)

### PR DESCRIPTION
**Pull request by hirakei1203**
I added a basic tooltip component.
Basic function is based on vue3-popper, OSS .
The below functions are implemented now!

- Placement
- Color style,
- Trigger type
- Disable Arrow (Not in document yet)

### CODE REVIEW

**Comment by cogor** [comment]
Can you replace vue3-popper with [Floating Vue](https://floating-vue.starpad.dev/) ?

**Comment by hirakei1203** [comment]
Ok! I will try to replace!

**Comment by cogor** [comment]
You can import `Tooltip` component and use it like that
```js
<template>
  <div class="flex items-start">
    <Tooltip>
      <a>Sponsor me</a>
      <template #popper>
        Help me fund my Open Source work!
      </template>
    </Tooltip>
  </div>
</template>

<script lang="ts" setup>
import type { PropType } from 'vue'
import type { TooltipPlacement, TooltipStyle } from './types'
import { Tooltip } from 'floating-vue'
import 'floating-vue/dist/style.css'

const props = defineProps({
    placement: {
      type: String as PropType<TooltipPlacement>,
      default: 'top',
    },
    colorStyle: {
      type: String  as PropType<TooltipStyle>,
      default: 'tooltip-dark',
    },
})
</script>
```

**Comment by hirakei1203** [comment]
@cogor 
Thank you for your help! I replace popper to Floating Vue.

**Comment by cogor** [comment]
> @cogor Thank you for your help! I replace popper to Floating Vue.

May you merge current master into your branch? 
We need it to resolve merge conflict

**Comment by hirakei1203** [comment]
Sorry. I uodated the pull request!

**Comment by cogor** [comment]
LGTM

**Pull request merged**
